name: rebuild and push container

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: aarnotenjin
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get Git commit timestamp
        run: echo "TIMESTAMP=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: Containerfile-bullseye-c-rs-py
          tags: aarnotenjin/debian-bullseye-c-rs-py:rev${{ github.sha }}
        env:
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}
